version: "3.5"

volumes:
  logica-sandbox-volume:
  mysql-volume:

services:

  keycloakmysql:
    image: mysql:5.7
    expose:
      - "3308"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password

  keycloak:
    image: jboss/keycloak
    volumes:
      - /Users/gopalmenon/volumes/realm.json:/Users/gopalmenon/volumes/realm.json
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=3308
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/Users/gopalmenon/volumes/realm.json
    command: ["-Djboss.http.port=8080", "-Dkeycloak.profile.feature.upload_scripts=enabled"]
    depends_on:
      - keycloakmysql

  sandbox-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - logica-sandbox-volume:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

  sandbox-manager-api:
    image: sandbox-manager-api:latest
    ports:
      - "12000:12000"
    environment:
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_NAME=sandman
      - DB_USER=root
      - DB_PASSWORD=password
    depends_on:
      - sandbox-mysql

  reference-auth:


networks:
  default:
    external: true
    name: logica-network
