spring:
  datasource:
    base_url: jdbc:mysql://${DB_HOST:sandboxdb.interop.community}:${DB_PORT:3306}
    username: ${DB_USER:system}
    password: ${DB_PASSWORD:password}
  mail:
    password: ${MAIL_PASSWORD:ThisIsNotTheRightPW}
#jasypt:
#  encryptor:
#    password: ${JASYPT_ENCRYPTOR_PASSWORD}
hspc:
  platform:
    authorization:
      url: https://${AUTH_HOST:auth.interop.community}:${AUTH_PORT:8060}
      adminAccess:
        clientSecret: ${CLIENT_SECRET:secret}
    messaging:
      sendEmail: true
      url: https://messaging.interop.community
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    jwt:
      key: ENC(3l6CQCaVY63m2Bbxq+s4laVEiR9UopFbyLJGs2ipib7+aXc4XoGV8A==)
    frontend: ${FRONT_END:https://sandbox.interop.community}

endpoints:
  health:
    sensitive: true

tier-rules:
  tierRuleList:
    FREE:
      sandboxes: 1
      apps: 2
      users: 2
      transactions: 50000
      storage: 1000
    DEVELOPER:
      sandboxes: 3
      apps: 5
      users: 3
      transactions: 100000
      storage: 5000
    TEAM:
      sandboxes: 10
      apps: 10
      users: 10
      transactions: 500000
      storage: 20000
#    ENTERPRISE:
#      sandboxes: 40
#      apps:
#      users:
#      transactions:
#      storage:

api_endpoint_index:
  prev:
    apiBaseURL_dstu2: https://api-v5-dstu2.interop.community
    apiBaseURL_stu3: https://api-v5-stu3.interop.community
    apiBaseURL_r4: https://api-v5-r4.interop.community
  current:
    apiBaseURL_dstu2: https://api-v8-dstu2.interop.community
    apiBaseURL_stu3: https://api-v8-stu3.interop.community
    apiBaseURL_r4: https://api-v8-r4.interop.community
    apiBaseURL_r5: https://api-v8-r5.interop.community