spring:
  datasource:
    base_url: jdbc:mysql://sandboxdb.interop.community:3306
    username: system
    password: ENC(eu7PppbSk0mHHUZjmjzZxPeU8X9aCckJ)
  mail:
    password: ENC(CO+ItH9klkYBTA3O9d3ltV/djiaWqFsBCA7jh86G9KzsxxIFpHjKKNr5PWecJv35OWz84ZTjs38=)
#jasypt:
#  encryptor:
#    password: ${JASYPT_ENCRYPTOR_PASSWORD}
hspc:
  platform:
    authorization:
      url: https://auth.interop.community
      adminAccess:
        clientSecret: ENC(gmMlVNIASfOKitTrkB/XrlVhV6e+zICBrsiEZ7Jiyv5fwO37wfLNKA6U4x7IJjtG)
    messaging:
      sendEmail: true
      url: https://messaging.interop.community
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    jwt:
      key: ENC(1j493gQNho0hZQ2g7t5a9ZZB3S+Tm5whhnjhr6NtPxAjTafqAE/iOQ==)
    frontend: https://sandbox.interop.community
    asymmetricKeysFolder: /KeyPair

endpoints:
  health:
    sensitive: true

tier-rules:
  tierRuleList:
    FREE:
      sandboxes: 1
      apps: 2
      users: 2
      transactions: 50000
      storage: 1000
    DEVELOPER:
      sandboxes: 3
      apps: 5
      users: 3
      transactions: 100000
      storage: 5000
    TEAM:
      sandboxes: 10
      apps: 10
      users: 10
      transactions: 500000
      storage: 20000
#    ENTERPRISE:
#      sandboxes: 40
#      apps:
#      users:
#      transactions:
#      storage:

api_endpoint_index:
  prev:
    apiBaseURL_dstu2: https://api-v5-dstu2.interop.community
    apiBaseURL_stu3: https://api-v5-stu3.interop.community
    apiBaseURL_r4: https://api-v5-r4.interop.community
  current:
    apiBaseURL_dstu2: https://api-v8-dstu2.interop.community
    apiBaseURL_stu3: https://api-v8-stu3.interop.community
    apiBaseURL_r4: https://api-v8-r4.interop.community
    apiBaseURL_r5: https://api-v8-r5.interop.community