server:
  port: ${port:9003}

endpoints:
  jmx:
    enabled: false

multipart:
  enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandman
    username: root
    password: password
#    persistenceUnitName: sandman
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
hspc:
  platform:
    hostUrl: http://localhost
    defaultPublicSandboxRoles: USER
    defaultPrivateSandboxRoles: USER,MANAGE_USERS,MANAGE_DATA

#    defaultSandboxCreatorRoles: ADMIN,MANAGE_USERS,MANAGE_DATA
#    defaultSystemRoles: USER
#    defaultSandboxVisibility: PUBLIC
    defaultSandboxCreatorRoles: ADMIN,MANAGE_USERS,MANAGE_DATA
    defaultSystemRoles: USER,CREATE_SANDBOX
    defaultSandboxVisibility: PRIVATE
    authorization:
      port: 8080
      context: /hspc-reference-authorization
      baseUrl: ${hspc.platform.hostUrl}:${hspc.platform.authorization.port}${hspc.platform.authorization.context}
      smart:
        launchUrl: ${hspc.platform.authorization.baseUrl}/Launch
    api:
      version1:
        port: 8080
        context: /hspc-reference-api
        baseUrl:  ${hspc.platform.hostUrl}:${hspc.platform.api.version1.port}${hspc.platform.api.version1.context}
      version2:
        port: 8081
        context: /hspc-reference-api
        baseUrl:  ${hspc.platform.hostUrl}:${hspc.platform.api.version2.port}${hspc.platform.api.version2.context}
      oauth2:
        clientId: hspc_resource_server
        clientSecret: secret
      sandboxManagementEndpointURL_1: ${hspc.platform.api.version1.baseUrl}/management/sandbox
      sandboxManagementEndpointURL_2: ${hspc.platform.api.version2.baseUrl}/management/sandbox
      oauthUserInfoEndpointURL: ${hspc.platform.authorization.baseUrl}/userinfo
      oauthClientEndpointURL: ${hspc.platform.authorization.baseUrl}/api/clients
      oauthUserLoginEndpointURL: ${hspc.platform.authorization.baseUrl}/j_spring_security_check
      oauthUser: admin
      oauthUserPassword: password
    messaging:
      port: 8080
      context: /hspc-reference-messaging
      sendEmail: false
      baseUrl: ${hspc.platform.hostUrl}:${hspc.platform.messaging.port}${hspc.platform.messaging.context}
      emailSenderEndpointURL: ${hspc.platform.messaging.baseUrl}/mailsender
      sandboxUserEndpointURL: ${hspc.platform.messaging.baseUrl}/sandboxuser

