spring:
  datasource:
    base_url: jdbc:mysql://sandboxdb-stage.interop.community:3306
    username: system
    password: ENC(E1mkzTQkF1mOsMiZap1WAs0icuMzPKMd)
  mail:
#    password: todo
#jasypt:
#  encryptor:
#    password: ${JASYPT_ENCRYPTOR_PASSWORD}
hspc:
  platform:
    authorization:
      url: https://auth-stage.interop.community
      adminAccess:
#        clientSecret: ENC(todo)
    messaging:
      sendEmail: true
      url: https://messaging.interop.community
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    jwt:
#      key: ENC(todo)
    frontend: https://sandbox-stage.interop.community

endpoints:
  health:
    sensitive: true

tier-rules:
  tierRuleList:
    FREE:
      sandboxes: 1
      apps: 2
      users: 2
      transactions: 50000
      storage: 1000
    DEVELOPER:
      sandboxes: 3
      apps: 5
      users: 3
      transactions: 100000
      storage: 5000
    TEAM:
      sandboxes: 10
      apps: 10
      users: 10
      transactions: 500000
      storage: 20000
#    ENTERPRISE:
#      sandboxes: 40
#      apps:
#      users:
#      transactions:
#      storage:

api_endpoint_index:
  prev:
    apiBaseURL_dstu2: https://api-v5-dstu2-stage.interop.community
    apiBaseURL_stu3: https://api-v5-stu3-stage.interop.community
    apiBaseURL_r4: https://api-v5-r4-stage.interop.community
  current:
    apiBaseURL_dstu2: https://api-v8-dstu2-stage.interop.community
    apiBaseURL_stu3: https://api-v8-stu3-stage.interop.community
    apiBaseURL_r4: https://api-v8-r4-stage.interop.community