endpoints:
  jmx:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandman?autoReconnect=true
    username: root
    password: password
#    persistenceUnitName: sandman
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

hspc:
  platform:
    user-support:
      key: c8381465-a7f8-4ecc-958d-ec296d6e8671
      endpoint: https://sandbox.hspconsortium.org/pwm