spring:
  datasource:
    base_url: jdbc:mysql://${DB_HOST:sandboxdb.interop.community}:${DB_PORT:3306}
    username: ${DB_USER:system}
    password: ${DB_PASSWORD:password}
  mail:
    password: ${MAIL_PASSWORD:ThisIsNotTheRightPW}
#jasypt:
#  encryptor:
#    password: ${JASYPT_ENCRYPTOR_PASSWORD}
hspc:
  platform:
    authorization:
      url: ${AUTH_HOST}
      adminAccess:
        clientSecret: ${CLIENT_SECRET:secret}
    messaging:
      sendEmail: true
      url: https://messaging.interop.community
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    jwt:
      key: ENC(1j493gQNho0hZQ2g7t5a9ZZB3S+Tm5whhnjhr6NtPxAjTafqAE/iOQ==)
    frontend: ${FRONT_END:https://sandbox.interop.community}
    asymmetricKeysFolder: /KeyPair

endpoints:
  health:
    sensitive: true

tier-rules:
  tierRuleList:
    FREE:
      sandboxes: 1
      apps: 2
      users: 2
      transactions: 50000
      storage: 1000
    DEVELOPER:
      sandboxes: 3
      apps: 5
      users: 3
      transactions: 100000
      storage: 5000
    TEAM:
      sandboxes: 10
      apps: 10
      users: 10
      transactions: 500000
      storage: 20000
#    ENTERPRISE:
#      sandboxes: 40
#      apps:
#      users:
#      transactions:
#      storage:

api_endpoint_index:
  prev:
    dstu2: 5
    stu3: 6
    r4: 7
    r5:
    apiBaseURL_dstu2: localhost
    apiBaseURL_stu3: localhost
    apiBaseURL_r4: localhost
    apiBaseURL_r5: localhost
  current:
    dstu2: 8
    stu3: 9
    r4: 10
    r5: 11
    apiBaseURL_dstu2: ${API_DSTU2_HOST}
    apiBaseURL_stu3: ${API_STU3_HOST}
    apiBaseURL_r4: ${API_R4_HOST}
    apiBaseURL_r5: ${API_R5_HOST}

aws:
  s3BucketName: interop-community-export