endpoints:
  jmx:
    enabled: false

multipart:
  enabled: true

spring:
  datasource:
    base_url: jdbc:mysql://localhost:3306
    url: ${spring.datasource.base_url}/sandman
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
hspc:
  platform:
    hostUrl: http://localhost
    # When a user is added to a PUBLIC sandbox, these are their default Sandbox Roles
    defaultPublicSandboxRoles: USER
    # When a user is added to a PRIVATE sandbox, these are their default Sandbox Roles
    defaultPrivateSandboxRoles: USER,MANAGE_USERS,MANAGE_DATA
    # When a user creates a brand new sandbox, these are the default Sandbox Roles they are given in the new sandbox
    defaultSandboxCreatorRoles: ADMIN,MANAGE_USERS,MANAGE_DATA
    # When a user logs in to Sandbox Manager for the first time, these are the System Roles they are given
    #    defaultSystemRoles: USER
    defaultSystemRoles: USER,CREATE_SANDBOX
    # When a user creates a brand new sandbox, this is the default visibility of the new sandbox
    #    defaultSandboxVisibility: PUBLIC
    defaultSandboxVisibility: PRIVATE
    authorization:
      port: 8080
      context: /hspc-reference-authorization
      baseUrl: ${hspc.platform.hostUrl}:${hspc.platform.authorization.port}${hspc.platform.authorization.context}
    api:
      version1:
        port: 8080
        context: /hspc-reference-api-v1
        baseUrl:  ${hspc.platform.hostUrl}:${hspc.platform.api.version1.port}${hspc.platform.api.version1.context}
      version2:
        port: 8080
        context: /hspc-reference-api-v2
        baseUrl:  ${hspc.platform.hostUrl}:${hspc.platform.api.version2.port}${hspc.platform.api.version2.context}
      version3:
        port: 8080
        context: /hspc-reference-api-v3
        baseUrl:  ${hspc.platform.hostUrl}:${hspc.platform.api.version3.port}${hspc.platform.api.version3.context}
      oauth2:
        clientId: hspc_resource_server
        clientSecret: secret
      oauthUserInfoEndpointURL: ${hspc.platform.authorization.baseUrl}/userinfo
      oauthClientEndpointURL: ${hspc.platform.authorization.baseUrl}/api/clients
      oauthUserLoginEndpointURL: ${hspc.platform.authorization.baseUrl}/j_spring_security_check
      oauthUser: admin
      oauthUserPassword: password
    messaging:
      port: 8080
      context: /hspc-reference-messaging/
      sendEmail: false
      baseUrl: ${hspc.platform.hostUrl}:${hspc.platform.messaging.port}${hspc.platform.messaging.context}
      emailSenderEndpointURL: ${hspc.platform.messaging.baseUrl}mailsender
      sandboxUserEndpointURL: ${hspc.platform.messaging.baseUrl}sandboxuser
    syntheticData:
#      fhirServerUrl: https://syntheticmass.mitre.org/fhir
       fhirServerUrl: http://localhost:8080/hspc-reference-api-v3/synthea2/open

