spring:
  datasource:
    base_url: jdbc:mysql://sandboxdb.hspconsortium.org:3306
    username: system
    password: ENC(lA/Ifn1Cm6pYGGydIXNQIa6n7ryn5A1+)
  mail:
    password: ENC(drTNjE8xqhmgZ9IUlTXQiwI4lJoCvV5GH5giC7OG5cl8g/FeQRRtbPQc5nkVmeiue8yqMHl37P8=) # ENC(HKnkcsBUqrbsBvPGwfjZvdnP3+tECpmt)
#jasypt:
#  encryptor:
#    password: ${JASYPT_ENCRYPTOR_PASSWORD}
hspc:
  platform:
    authorization:
      url: https://auth.hspconsortium.org
      adminAccess:
        clientSecret: ENC(PKNLyDyXbOFXKGnnK7bJlr1Isn/t3xJ6gGnEC+4f4yhDsK7A2eM/jL72WLuRQFuYy4cZt8JKpcxLmIV/exV2/eVaWvh8whJresSigPwsNhKhSdiZl6hS9Er+dLy1pARN)
    api:
      version5:
        baseUrl: https://api-v5-dstu2.hspconsortium.org
      version6:
        baseUrl: https://api-v5-stu3.hspconsortium.org
      version7:
        baseUrl: https://api-v5-r4.hspconsortium.org
      version8:
        baseUrl: https://api-v8-dstu2.hspconsortium.org
      version9:
        baseUrl: https://api-v8-stu3.hspconsortium.org
      version10:
        baseUrl: https://api-v8-r4.hspconsortium.org
    messaging:
      sendEmail: true
      url: https://messaging.hspconsortium.org
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    jwt:
      key: ENC(32oeS4V7gZfqPfndJXegT0cEHIU805Xbn/2qt5p8/5WriF926qEn58gJJdy+6+6ayCAJYN09y43R/9tcIktIXA3Yg6scHRMLzfx+9a4eybo=)
    frontend: https://sandbox.hspconsortium.org

endpoints:
  health:
    sensitive: true

tier-rules:
  tierRuleList:
    FREE:
      sandboxes: 1
      apps: 2
      users: 2
      transactions: 50000
      storage: 1000
    DEVELOPER:
      sandboxes: 3
      apps: 5
      users: 3
      transactions: 100000
      storage: 5000
    TEAM:
      sandboxes: 10
      apps: 10
      users: 10
      transactions: 500000
      storage: 20000
#    ENTERPRISE:
#      sandboxes: 40
#      apps:
#      users:
#      transactions:
#      storage: