spring:
  datasource:
    base_url: jdbc:mysql://sandboxdb.hspconsortium.org:3306
    username: system
    password: ENC(Ug+CO2kXMtyYJNrRagiJOEVBKJFshM4K)
  mail:
    password: ENC(HKnkcsBUqrbsBvPGwfjZvdnP3+tECpmt)
#jasypt:
#  encryptor:
#    password: ${JASYPT_ENCRYPTOR_PASSWORD}
hspc:
  platform:
    authorization:
      url: https://auth2.hspconsortium.org
      adminAccess:
        clientSecret: ENC(6kmKr5Yip2z6a59Oq3srEoP2L9bx+VuL/QGarR6M1GhMjhMWngZk+tXUvA22tACRfSbCPj0f/wrzcqN0N6QsOGwoN8wbbQSySOzQ82tuFTMz+Phaw0+61cvTX+cvZ/6P)
    api:
      version1:
        baseUrl: https://api.hspconsortium.org
      version2:
        baseUrl: https://api2.hspconsortium.org
      version3:
        baseUrl: https://api3.hspconsortium.org
      version4:
        baseUrl: https://api-stu3.hspconsortium.org
      version5:
        baseUrl: https://api-v5-dstu2.hspconsortium.org
      version6:
        baseUrl: https://api-v5-stu3.hspconsortium.org
      version7:
        baseUrl: https://api-v5-r4.hspconsortium.org
    messaging:
      sendEmail: true
      url: https://messaging.hspconsortium.org
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    jwt:
      key: ENC(Mv+rOiWWXL8EjK31WoY4N2QCW+18S8NBHA8g46xeTGNxfvVJwzW0bU+qXrdUFDIAcpOb7wR5/bfzLwUB28m88n5/3BEDuPLKx7DohkSx5ds=)
