spring:
  datasource:
    base_url: jdbc:mysql://sandboxdb-test.hspconsortium.org
    username: hspctest
    password: ENC(kYqZKAjsHHSeqTtyGKzNsrrIUWdjXiXl)
  mail:
    password: ENC(G617hEtHdDqtzbpE9CtoYnopRfcrBqK8)
hspc:
  platform:
    authorization:
      url: https://auth-test.hspconsortium.org
      adminAccess:
        clientSecret: secret
    api:
      version1:
        baseUrl: https://api-test.hspconsortium.org
      version2:
        baseUrl: https://api2-test.hspconsortium.org
      version3:
        baseUrl: https://api3-test.hspconsortium.org
      version4:
        baseUrl: https://api-stu3-test.hspconsortium.org
      version5:
        baseUrl: https://api-dstu2-test.hspconsortium.org
      version6:
        baseUrl: https://api-stu3-test.hspconsortium.org
      version7:
        baseUrl: https://api-v5-r4-test.hspconsortium.org
    messaging:
      sendEmail: true
      url: https://messaging-test.hspconsortium.org
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    jwt:
      key: devKeyDoNotUseInProductionShouldBeOverwrittenInProdConfiguration
