spring:
  datasource:
    base_url: jdbc:mysql://sandboxdb-test.hspconsortium.org:3306
    username: sandman_api
    password: ENC(rHDEF2U5A5X9o/Jca3P9CkRvYKs1mSTP)
  mail:
    password: ENC(DqcAHgFLNO56JPc9mFhONpf93MkJrZtxjMDD85keUy9N/En58H5ReTao6cnuKk39WXij1zfa8Z8=)
hspc:
  platform:
    authorization:
      url: https://auth-test.hspconsortium.org
      adminAccess:
        clientSecret: secret
    messaging:
      sendEmail: true
      url: https://messaging-test.hspconsortium.org
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    jwt:
      key: devKeyDoNotUseInProductionShouldBeOverwrittenInProdConfiguration
    frontend: https://sandbox-test.hspconsortium.org
tier-rules:
  tierRuleList:
    FREE:
      sandboxes: 1
      apps: 2
      users: 2
      transactions: 50000
      storage: 1000
    DEVELOPER:
      sandboxes: 3
      apps: 5
      users: 3
      transactions: 100000
      storage: 5000
    TEAM:
      sandboxes: 10
      apps: 10
      users: 10
      transactions: 500000
      storage: 20000
#    ENTERPRISE:
#      sandboxes: 40
#      apps:
#      users:
#      transactions:
#      storage:

api_endpoint_index:
  prev:
    apiBaseURL_dstu2: https://api-v5-dstu2-test.hspconsortium.org
    apiBaseURL_stu3: https://api-v5-stu3-test.hspconsortium.org
    apiBaseURL_r4: https://api-v5-r4-test.hspconsortium.org
  current:
    apiBaseURL_dstu2: https://api-v8-dstu2-test.hspconsortium.org
    apiBaseURL_stu3: https://api-v8-stu3-test.hspconsortium.org
    apiBaseURL_r4: https://api-v8-r4-test.hspconsortium.org