endpoints:
  jmx:
    enabled: false

multipart:
  enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandman
    username: root
    password: password
#    persistenceUnitName: sandman
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
hspc:
  platform:
    api:
      sandboxManagementEndpointURL: http://localhost:8080/hspc-reference-api/management/sandbox
      oauthUserInfoEndpointURL: http://localhost:8080/hspc-reference-authorization/userinfo
      oauthClientEndpointURL: http://localhost:8080/hspc-reference-authorization/api/clients
      oauthUser: admin
      oauthUserPassword: FH!R4a11

