spring:
  datasource:
    base_url: jdbc:mysql://sandboxdb-test.hspconsortium.org:3306
    username: sandman_api
    password: ENC(rHDEF2U5A5X9o/Jca3P9CkRvYKs1mSTP)
  mail:
#    password: ENC(G617hEtHdDqtzbpE9CtoYnopRfcrBqK8)
    password: ENC(baeMFVFHbe1f88GRev1Vgb25s2k+BwNjZbmGvUN5/EquOSZMdYS9Bcpb5KxrNtTHAHgNkAG+dpU=)
hspc:
  platform:
    authorization:
      url: https://auth-test.hspconsortium.org
      adminAccess:
        clientSecret: secret
    api:
      version1:
        baseUrl: https://api-test.hspconsortium.org
      version2:
        baseUrl: https://api2-test.hspconsortium.org
      version3:
        baseUrl: https://api3-test.hspconsortium.org
      version4:
        baseUrl: https://api-stu3-test.hspconsortium.org
      version5:
        baseUrl: https://api-v5-dstu2-test.hspconsortium.org
      version6:
        baseUrl: https://api-v5-stu3-test.hspconsortium.org
      version7:
        baseUrl: https://api-v5-r4-test.hspconsortium.org
    messaging:
      sendEmail: true
      url: https://messaging-test.hspconsortium.org
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    jwt:
      key: devKeyDoNotUseInProductionShouldBeOverwrittenInProdConfiguration
    frontend: https://sandbox-test.hspconsortium.org
tier-rules:
  tierRuleList:
    FREE:
      sandboxes: 1
      apps: 2
      users: 2
      transactions: 50000
      storage: 1000
    DEVELOPER:
      sandboxes: 3
      apps: 5
      users: 3
      transactions: 100000
      storage: 5000
    TEAM:
      sandboxes: 10
      apps: 10
      users: 10
      transactions: 500000
      storage: 20000
#    ENTERPRISE:
#      sandboxes: 40
#      apps:
#      users:
#      transactions:
#      storage: