spring:
  datasource:
    base_url: jdbc:mysql://sandboxdb-test.logicahealth.org:3306
    username: system
    password: ENC(eTe28H24x7ir3WTFLKeYurHJHMn3NeRb)
#    username: sandman_api
#    password: ENC(rHDEF2U5A5X9o/Jca3P9CkRvYKs1mSTP)
  # TODO: We need understand the reason for why the sandman_api restricted account was used here. - SS - 2020-06-02
  mail:
    password: ENC(cYJTFXqQKNniUyjsHV4VBU2ig7E1oxEvQy4saGPhV/LA8OMJ5GFPaJM3UPBe5kw3DPXPxmRsAqw=)
hspc:
  platform:
    authorization:
      url: https://auth-test.logicahealth.org
      adminAccess:
        clientSecret: ENC(38zd6mj1buFAIQMh+3wMKi51Uwglzr2MYjmuQsTruQ7P/DoyTs6UmPXtlwjpbOC2kSEgIYPwAo376GqXvY8HETj4aKe4gWQDoyTcz1aK/zuUgC10mCuMnKNE1BHtC7Nt)   #secret
    messaging:
      sendEmail: true
      url: https://messaging-test.logicahealth.org
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    jwt:
      key: devKeyDoNotUseInProductionShouldBeOverwrittenInProdConfiguration
    frontend: https://sandbox-test.logicahealth.org
tier-rules:
  tierRuleList:
    FREE:
      sandboxes: 1
      apps: 2
      users: 2
      transactions: 50000
      storage: 1000
    DEVELOPER:
      sandboxes: 3
      apps: 5
      users: 3
      transactions: 100000
      storage: 5000
    TEAM:
      sandboxes: 10
      apps: 10
      users: 10
      transactions: 500000
      storage: 20000
#    ENTERPRISE:
#      sandboxes: 40
#      apps:
#      users:
#      transactions:
#      storage:

api_endpoint_index:
  prev:
    apiBaseURL_dstu2: https://api-v5-dstu2-test.logicahealth.org
    apiBaseURL_stu3: https://api-v5-stu3-test.logicahealth.org
    apiBaseURL_r4: https://api-v5-r4-test.logicahealth.org
  current:
    apiBaseURL_dstu2: https://api-v8-dstu2-test.logicahealth.org
    apiBaseURL_stu3: https://api-v8-stu3-test.logicahealth.org
    apiBaseURL_r4: https://api-v8-r4-test.logicahealth.org