server:
  port: 12000
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
# If we want to have paths for each project uncomment this
# context-path: /api

spring:
  application:
    name: HSPC Sandbox Manager
  datasource:
    base_url: jdbc:mysql://localhost:3306
    my_schema: sandman
    url: ${spring.datasource.base_url}/${spring.datasource.my_schema}
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
    initialSize: 1
    maxActive: 5
  jpa:
    hibernate:
      # Do not commit with a different value (update, create, etc)
      # Instead, use flywaydb scripts at /src/main/resources/db/mysql/migrate
      ddl-auto: validate
      show-sql: false
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

flyway:
  locations: db/mysql/migration
  out-of-order: true

security:
  oauth2:
    resource:
      userInfoUri: ${hspc.platform.authorization.url}/userinfo
      token-info-uri: ${hspc.platform.authorization.url}/token

hspc:
  platform:
    # When a user is added to a PUBLIC sandbox, these are their default Sandbox Roles
    defaultPublicSandboxRoles: USER
    # When a user is added to a PRIVATE sandbox, these are their default Sandbox Roles
    defaultPrivateSandboxRoles: USER,MANAGE_USERS,MANAGE_DATA
    # When a user creates a brand new sandbox, these are the default Sandbox Roles they are given in the new sandbox
    defaultSandboxCreatorRoles: ADMIN,MANAGE_USERS,MANAGE_DATA
    # When a user logs in to Sandbox Manager for the first time, these are the System Roles they are given
    #    defaultSystemRoles: USER
    defaultSystemRoles: USER,CREATE_SANDBOX
    # When a user creates a brand new sandbox, this is the default visibility of the new sandbox
    #    defaultSandboxVisibility: PUBLIC
    defaultSandboxVisibility: PRIVATE
    authorization:
      url: http://localhost:8060
      tokenEndpoint: ${hspc.platform.authorization.url}/token
      authorizeEndpoint: ${hspc.platform.authorization.url}/authorize
      adminAccess:
        clientId: sandman_admin
        clientSecret: secret
    api:
      version1:
        baseUrl: http://localhost:8071/
      version2:
        baseUrl: http://localhost:8072/
      version3:
        baseUrl: http://localhost:8073/
      version4:
        baseUrl: http://localhost:8074/
      oauthUserInfoEndpointURL: ${hspc.platform.authorization.url}/userinfo
      oauthClientEndpointURL: ${hspc.platform.authorization.url}/api/clients
    messaging:
      sendEmail: false
      url: http://localhost:8091
      emailSenderEndpointURL: ${hspc.platform.messaging.url}/mailsender
    syntheticData:
#      fhirServerUrl: https://syntheticmass.mitre.org/fhir
       fhirServerUrl: ${hspc.platform.api.version3.baseUrl}/synthea2/open
    jwt:
      key: devKeyDoNotUseInProductionShouldBeOverwrittenInProdConfiguration
      signatureAlgorithm: HS256

multipart:
  enabled: true

