server:
  port: 12000
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

spring:
  application:
    name: HSPC Sandbox Manager
  profiles:
    active:
  datasource:
    base_url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}
    my_schema: ${DB_NAME:sandman}
    url: ${spring.datasource.base_url}/${spring.datasource.my_schema}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
    initialSize: 1
    maxActive: 5
  jpa:
    hibernate:
      # Do not commit with a different value (update, create, etc)
      # Instead, use flywaydb scripts at /src/main/resources/db/mysql/migrate
      ddl-auto: validate
      show-sql: false
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  mail:
    sender:
      address: no-reply@hspconsortium.org
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
          quitwait: false
    username: no-reply@hspconsortium.org
    password: ThisIsNotTheRightPW
  thymeleaf:
      cache: false
      check-template: true
      check-template-location: true
      content-type: text/html
      enabled: true
      encoding: UTF-8
      prefix: classpath:/templates/
      suffix: .html

flyway:
  locations: classpath:db/migration/{vendor}
  out-of-order: true

security:
  oauth2:
    resource:
      userInfoUri: ${hspc.platform.authorization.url}/userinfo
      token-info-uri: ${hspc.platform.authorization.url}/token

hspc:
  platform:
    # When a user is added to a PUBLIC sandbox, these are their default Sandbox Roles
    defaultPublicSandboxRoles: USER
    # When a user is added to a PRIVATE sandbox, these are their default Sandbox Roles
    defaultPrivateSandboxRoles: USER,MANAGE_USERS,MANAGE_DATA
    # When a user creates a brand new sandbox, these are the default Sandbox Roles they are given in the new sandbox
    defaultSandboxCreatorRoles: ADMIN,MANAGE_USERS,MANAGE_DATA
    # When a user logs in to Sandbox Manager for the first time, these are the System Roles they are given
    #    defaultSystemRoles: USER
    defaultSystemRoles: USER,CREATE_SANDBOX
    # When a user creates a brand new sandbox, this is the default visibility of the new sandbox
    #    defaultSandboxVisibility: PUBLIC
    defaultSandboxVisibility: PRIVATE
    authorization:
      url: http://${AUTH_HOST:localhost}:${AUTH_PORT:8060}
      tokenEndpoint: ${hspc.platform.authorization.url}/token
      authorizeEndpoint: ${hspc.platform.authorization.url}/authorize
      adminAccess:
        clientId: sandman_admin
        clientSecret: secret
    api:
      version1:
        baseUrl: http://localhost:8071
      version2:
        baseUrl: http://localhost:8072
      version3:
        baseUrl: http://localhost:8073
      version4:
        baseUrl: http://localhost:8074
      version5:
        baseUrl: http://${API_DSTU2_HOST:localhost}:${API_DSTU2_PORT:8075}
      version6:
        baseUrl: http://${API_STU3_HOST:localhost}:${API_STU3_PORT:8076}
      version7:
        baseUrl: http://${API_R4_HOST:localhost}:${API_R4_PORT:8077}
      oauthUserInfoEndpointURL: ${hspc.platform.authorization.url}/userinfo
      oauthClientEndpointURL: ${hspc.platform.authorization.url}/api/clients
    messaging:
      sendEmail: false
    syntheticData:
#      fhirServerUrl: https://syntheticmass.mitre.org/fhir
       fhirServerUrl: ${hspc.platform.api.version3.baseUrl}/synthea2/open
    jwt:
      key: devKeyDoNotUseInProductionShouldBeOverwrittenInProdConfiguration
      signatureAlgorithm: HS256

multipart:
  enabled: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES

endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false

cloud:
  aws:
    cloudwatch:
      namespace: sandbox-manager-api
    region:
      static: us-west-2
    stack:
      auto: false

expiration-message: FHIR R4 DFC available on trial basis. This sandbox will be unavailable after Aug 31, 2018.
expiration-date: 2018-09-01

default-public-apps: cds-hooks-sandbox, hspc-bilirubin-risk-chart, hspc-my-web-app

#tier-rules:
#  tierRuleList:
#    FREE:
#      sandboxes: 1
#      apps: 2
#      users: 2
#      transactions: 50000
#      storage: 1000
#    DEVELOPER:
#      sandboxes: 3
#      apps: 5
#      users: 3
#      transactions: 100000
#      storage: 5000
#    TEAM:
#      sandboxes: 10
#      apps: 10
#      users: 10
#      transactions: 500000
#      storage: 20000
#    ENTERPRISE:
#      sandboxes: 40
#      apps:
#      users:
#      transactions:
#      storage: